Repository GoogleCloudPlatform/compute-image-import, pull requests merged in 2022-11, with the labels that each got.

#70 Update _config.yml
  docs/_config.yml
Labels: size/XS, approved, lgtm

#71 pre-install protobuf~=3.1 in the worker image
  daisy_workflows/image_build/debian/debian_worker.sh
Labels: size/XS, approved, lgtm

#73 Use upgraded worker with libguestFS v1.48 in rhel-8 translation
  daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json
Labels: size/XS, approved, lgtm

#74 Use worker image with pre installed protobuf in the inspection workflow
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
  daisy_workflows/image_import/inspection/boot-inspect.wf.json
Labels: approved, lgtm, size/M

#75 Nested virtualization.
  cli_tools/common/image/importer/request.go
  cli_tools/common/image/importer/request_test.go
  cli_tools/common/utils/daisyutils/daisy_utils.go
  cli_tools/common/utils/daisyutils/daisy_worker.go
  cli_tools/common/utils/daisyutils/workflow_hook_enable_nested_virtualization.go
  cli_tools/common/utils/daisyutils/workflow_hook_enable_nested_virtualization_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/utils.go
  cli_tools/gce_ovf_export/domain/args.go
  cli_tools/gce_ovf_import/domain/ovf_import_params.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/main_test.go
  cli_tools/gce_ovf_import/multi_disk_importer/request_builder.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/main.go
  cli_tools/gce_vm_image_import/cli/args.go
  cli_tools/gce_vm_image_import/cli/args_test.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/export/image_export_test_suite.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
Labels: approved, lgtm, size/XL

#76 Fix comment.
  cli_tools/common/utils/daisyutils/workflow_hook_enable_nested_virtualization.go
Labels: size/XS, approved, lgtm

#72 Integration test for workers and translation.
  daisy_integration_tests/debian_10_worker.wf.json
  daisy_integration_tests/debian_11_worker.wf.json
  daisy_integration_tests/debian_worker.subwf.json
Labels: approved, lgtm, size/L

#69 Add support for RHEL-9 OS
  cli_tools/common/utils/daisyutils/daisy_utils.go
  cli_tools/common/utils/daisyutils/daisy_utils_test.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_workflows/image_import/enterprise_linux/translate_rhel_9_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_9_licensed.wf.json
  daisy_workflows/image_import/inspection/tests/test-data/images/gcp-image-rhel-9-v20220920.yaml
Labels: approved, lgtm, size/L

#77 Dont fail if dracut or depmod commands failed for SUSE and Enterprise Linux
  daisy_workflows/image_import/enterprise_linux/translate.py
  daisy_workflows/image_import/suse/suse_import/translate.py
  daisy_workflows/linux_common/utils/common.py
Labels: approved, lgtm, size/L

#78 ImageImport replace Centos-8 images in e2e tests by other Enterprise-Linux OSes
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
Labels: approved, lgtm, size/S

#79 Fix the IN_USE_ADDRESSES quota error.
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
Labels: approved, lgtm, size/M

#80 allow-debian-import-to-proceed-if-the-image-does-not-has-wget-or-curl-installed
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_workflows/image_import/debian/translate.py
Labels: approved, lgtm, size/S

#81 Enable nested virtualization by default.
  cli_tools/gce_onestep_image_import/onestep_importer/importer.go
  cli_tools/gce_ovf_export/domain/args.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_vm_image_export/main.go
  cli_tools/gce_vm_image_import/cli/args.go
  cli_tools/gce_vm_image_import/cli/args_test.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/export/image_export_test_suite.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/M
