Repository GoogleCloudPlatform/compute-image-import, pull requests merged in 2022-09, with the labels that each got.

#57 ImageImport_attach_disks_to_inspection_worker_instance_after_its_created
  daisy_workflows/image_import/inspection/README.md
  daisy_workflows/image_import/inspection/boot-inspect.wf.json
  daisy_workflows/image_import/inspection/daisy-shim.sh
  daisy_workflows/image_import/inspection/src/boot_inspect/cli.py
Labels: approved, lgtm, size/L

#58 Image Import: Fix inspection module tests.
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
Labels: approved, lgtm, size/S

#59 ImageImport_upgrade_translation_worker_instance_os_version_for_enterp…
  daisy_workflows/image_import/enterprise_linux/translate_centos_7.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_8.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_7_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rocky_8.wf.json
Labels: approved, lgtm, size/S

#60 Fix E2E SLES tests.
  daisy_workflows/image_import/suse/suse_import/translate.py
Labels: approved, lgtm, size/S

#61 Fix SLES PAYG E2E tests.
  daisy_workflows/image_import/suse/suse_import/translate.py
Labels: size/XS, approved, lgtm

#62 Image-Import drop e2e tests that tests importing centos8
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_integration_tests/daisy_e2e.test.gotmpl
Labels: approved, lgtm, size/S

#63 Fix quotes.
  daisy_workflows/image_import/inspection/daisy-shim.sh
Labels: size/XS, approved, lgtm

#64 Inspection_downgrade_worker_OS_to_Debian_10
  daisy_workflows/image_import/inspection/boot-inspect.wf.json
Labels: size/XS, approved, lgtm

#65 Remove Zypper update from the flow.
  daisy_workflows/image_import/suse/suse_import/translate.py
Labels: approved, lgtm, size/S

#66 ImageImport_remove_windows_11_x86_mapping
  cli_tools/common/utils/daisyutils/daisy_utils.go
Labels: size/XS, approved, lgtm
