Repository GoogleCloudPlatform/compute-image-import, pull requests merged in 2022-12, with the labels that each got.

#82 deprecate CentOS-8
  cli_tools/common/utils/daisyutils/daisy_utils.go
  cli_tools/common/utils/daisyutils/daisy_utils_test.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  daisy_integration_tests/centos_8_translate.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_8.wf.json
  daisy_workflows/image_import/inspection/tests/test-data/images/docker-image-centos-8.1.1911.yaml
  daisy_workflows/image_import/inspection/tests/test-data/images/docker-image-centos-8.2.2004.yaml
  daisy_workflows/image_import/inspection/tests/test-data/images/docker-image-centos-latest.yaml
  daisy_workflows/image_import/inspection/tests/test-data/images/gcp-image-centos-8-v20200714.yaml
  docs/image-import.md
Labels: approved, lgtm, size/L

#84 Nested virtualization in E2E post translate.
  cli_tools_tests/e2e/gce_image_import_export/test_suites/scripts/post_translate_test.wf.json
Labels: size/XS, approved, lgtm

#83 Detect available machine series in the project.
  cli_tools/common/disk/mocks/mock_inspect.go
  cli_tools/common/image/importer/mocks/importer_mocks.go
  cli_tools/common/image/importer/mocks/source_mocks.go
  cli_tools/common/image/importer/request.go
  cli_tools/common/image/importer/request_test.go
  cli_tools/common/utils/daisyutils/daisy_utils.go
  cli_tools/common/utils/daisyutils/daisy_worker.go
  cli_tools/common/utils/daisyutils/daisy_worker_test.go
  cli_tools/common/utils/daisyutils/workflow_hook_update_machine_types.go
  cli_tools/common/utils/daisyutils/workflow_hook_update_machine_types_test.go
  cli_tools/common/utils/param/machine_series_detector.go
  cli_tools/common/utils/param/machine_series_detector_test.go
  cli_tools/common/utils/param/populator.go
  cli_tools/common/utils/param/populator_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_args.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/test_utils_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/utils.go
  cli_tools/gce_ovf_export/domain/args.go
  cli_tools/gce_ovf_export/domain/args_test.go
  cli_tools/gce_ovf_export/domain/mocks/mock_instance_disks_exporter.go
  cli_tools/gce_ovf_export/domain/mocks/mock_instance_export_cleaner.go
  cli_tools/gce_ovf_export/domain/mocks/mock_instance_export_preparer.go
  cli_tools/gce_ovf_export/domain/mocks/mock_ovf_descriptor_generator.go
  cli_tools/gce_ovf_export/domain/mocks/mock_ovf_export_param_populator.go
  cli_tools/gce_ovf_export/domain/mocks/mock_ovf_export_param_validator.go
  cli_tools/gce_ovf_export/domain/mocks/mock_ovf_manifest_generator.go
  cli_tools/gce_ovf_export/domain/test_data.go
  cli_tools/gce_ovf_export/exporter/param_populator.go
  cli_tools/gce_ovf_export/exporter/param_populator_test.go
  cli_tools/gce_ovf_import/domain/ovf_import_params.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/multi_disk_importer/request_builder.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/main.go
  cli_tools/gce_vm_image_import/cli/args.go
  cli_tools/gce_vm_image_import/cli/args_test.go
  cli_tools/gce_vm_image_import/cli/cli.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools/mocks/mock_logger.go
  cli_tools/mocks/mock_machine_series_detector.go
  cli_tools/mocks/mock_param_populator.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/export/image_export_test_suite.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  cli_tools_tests/e2e/gce_windows_upgrade/test_suites/windows_upgrade/windows_upgrade_test_suite.go
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
  daisy_workflows/image_build/debian/debian_worker.wf.json
Labels: approved, lgtm, size/XXL

#86 Allow importing AWS images without specifying --os
  cli_tools/gce_onestep_image_import/onestep_importer/importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer_test.go
  gce_onestep_image_import.Dockerfile
Labels: approved, lgtm, size/S

#87 SUSE byol translation don't fail when SUSEConnect commands failed
  daisy_workflows/image_import/suse/suse_import/translate.py
Labels: approved, lgtm, size/S
