Repository GoogleCloudPlatform/compute-image-import, pull requests merged in 2022-08, with the labels that each got.

#49 Update Debian worker for RHEL 8 imports
  daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json
Labels: size/XS, approved, lgtm

#50 ImageImport_fix_opensuse_module_test
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
Labels: size/XS, approved, lgtm

#48 fix daisy workflow links in the readme file
  README.md
Labels: approved, lgtm, size/S

#52 Start using N2 instances for SLES import.
  daisy_workflows/image_import/suse/translate_opensuse_15.wf.json
  daisy_workflows/image_import/suse/translate_suse.wf.json
Labels: size/XS, approved, lgtm

#54 Use N1 instances for now due to quotas limitations.
  daisy_workflows/image_import/suse/translate_opensuse_15.wf.json
  daisy_workflows/image_import/suse/translate_suse.wf.json
Labels: size/XS, approved, lgtm

#51 Update daisy workflow readme for image import
  README.md
  daisy_workflows/README.md
Labels: approved, lgtm, size/S

#53 ImageImport_add_support_for_windows_11
  cli_tools/common/image/importer/process_planner.go
  cli_tools/common/utils/daisyutils/daisy_utils.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
  daisy_workflows/image_import/windows/translate.ps1
Labels: approved, lgtm, size/M

#55 Allow SUSE import to proceed when /etc/resolv.conf is immutable
  daisy_workflows/image_import/enterprise_linux/translate.py
  daisy_workflows/image_import/suse/suse_import/translate.py
  daisy_workflows/linux_common/utils/common.py
Labels: approved, lgtm, size/S

#56 Attach disks to the worker after it is created.
  cli_tools/common/image/importer/bootable_disk_processor.go
  cli_tools/common/image/importer/bootable_disk_processor_test.go
  cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/scripts/ovf_import_test_3_disks.sh
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_import_e2e_common.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  daisy_workflows/image_import/enterprise_linux/translate.py
  daisy_workflows/image_import/enterprise_linux/translate_el.wf.json
Labels: approved, lgtm, size/L
