Repository GoogleCloudPlatform/compute-image-import, pull requests merged in 2023-05, with the labels that each got.

#100 upgrage-image-import-export-tools-builder-executor-base-image-to-debian-11
  gce_onestep_image_import.Dockerfile
  gce_ovf_export.Dockerfile
  gce_ovf_import.Dockerfile
  gce_vm_image_import.Dockerfile
Labels: size/XS, approved

#101 Fix Module Tests for Centos Stream 8/9
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
Labels: size/XS, approved, lgtm

#102 Use Debian-11 instead of Debian-9 in e2e tests as Debian-9 is EOL now
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
Labels: approved, lgtm, size/L

#103 Add --skip-broken flag when needed to EL yum install commands
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: approved, lgtm, size/S

#104 Removing TCP 80 check
  daisy_workflows/image_import/windows/network.ps1
Labels: size/XS, approved, lgtm
