Repository GoogleCloudPlatform/compute-image-import, pull requests merged in 2023-10, with the labels that each got.

#124 Upgrade libguestFS version used for CentOS stream by upgrading worker-image version
  daisy_workflows/image_import/enterprise_linux/translate_centos_stream_8.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_stream_9.wf.json
Labels: approved, size/S

#125 Allow importing CentOS with no enabled repos when no-guest-env flag is enabled
  daisy_integration_tests/centos_7_translate_with_no_enabled_repos.json
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: approved, lgtm, size/M

#127 fix-daisy-integration-tests-build-failure
  daisy_integration_tests/daisy_e2e.test.gotmpl
Labels: size/XS, approved

#128 updating Windows driver location to win6.3-signed-nonvme
  daisy_workflows/image_import/windows/translate_windows_10_x64_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_2012_r2.wf.json
  daisy_workflows/image_import/windows/translate_windows_2012_r2_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_2016.wf.json
  daisy_workflows/image_import/windows/translate_windows_2016_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_2019.wf.json
  daisy_workflows/image_import/windows/translate_windows_2019_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_2022.wf.json
  daisy_workflows/image_import/windows/translate_windows_2022_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_8_x64_byol.wf.json
Labels: approved, lgtm, size/S

#129 Fix Docker Files issue to install latest gcsfuse version
  e2e_test_base.Dockerfile
  gce_onestep_image_import.Dockerfile
  gce_ovf_export.Dockerfile
  gce_ovf_import.Dockerfile
  gce_vm_image_import.Dockerfile
  gcsfuse-apt-key.gpg
Labels: approved, lgtm, size/M
