Repository GoogleCloudPlatform/compute-image-import, pull requests merged in 2024-11, with the labels that each got.

#155 Update bucket attributes in order to disable soft delete
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/storage/scratch_bucket_creator.go
  cli_tools/common/utils/storage/scratch_bucket_creator_test.go
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/mocks/mock_storage_client.go
Labels: approved, lgtm, size/M

#156 Revert "Update bucket attributes in order to disable soft delete"
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/storage/scratch_bucket_creator.go
  cli_tools/common/utils/storage/scratch_bucket_creator_test.go
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/mocks/mock_storage_client.go
Labels: approved, lgtm, size/M

#158 Update OWNERS_ALIASES - add shtarkmang
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#157 Reapply "Update bucket attributes in order to disable soft delete (#1…
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/storage/scratch_bucket_creator.go
  cli_tools/common/utils/storage/scratch_bucket_creator_test.go
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/mocks/mock_storage_client.go
Labels: needs-ok-to-test, approved, lgtm, size/L

#161 Use Debian12 base containers in export flows
  gce_ovf_export.Dockerfile
  gce_vm_image_export.Dockerfile
Labels: size/XS, approved, lgtm

#159 Remove soft deletion when GCS bucket is provided as an arg
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/param/param_utils.go
  cli_tools/common/utils/param/populator_test.go
  cli_tools/common/utils/storage/scratch_bucket_creator.go
  cli_tools/mocks/mock_scratch_bucket_creator.go
Labels: approved, lgtm, size/M

#163 Increase verify-output timeout in export tests
  daisy_integration_tests/image_export_nondefault_network_latest.wf.json
  daisy_integration_tests/image_export_release.wf.json
  daisy_integration_tests/image_export_subnetwork_latest.wf.json
Labels: size/XS, approved, lgtm
