Repository GoogleCloudPlatform/compute-image-import, pull requests merged in 2024-12, with the labels that each got.

#164 Remove build for Debian 10 worker
  debian_worker_cloudbuild.yaml
Labels: approved, lgtm, size/S

#166 Use the latest debian 11 worker
  cli_tools/common/utils/daisyutils/daisy_utils_test.go
  daisy_integration_tests/create_random_data_image.subwf.json
  daisy_integration_tests/image_export_vmdk_given_size_verify.subwf.json
  daisy_workflows/image_import/debian/translate_debian.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_7.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_stream_8.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_stream_9.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_7_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_9_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_9_licensed.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rocky_8.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rocky_9.wf.json
  daisy_workflows/image_import/import_image.wf.json
  daisy_workflows/image_import/inspection/boot-inspect.wf.json
Labels: approved, lgtm, size/M

#167 Revert "Use Debian12 base containers in export flows (#161)"
  gce_ovf_export.Dockerfile
  gce_vm_image_export.Dockerfile
Labels: size/XS, approved, lgtm

#168 Revert gcs bucket update
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/param/param_utils.go
  cli_tools/common/utils/param/populator_test.go
  cli_tools/common/utils/storage/scratch_bucket_creator.go
  cli_tools/common/utils/storage/scratch_bucket_creator_test.go
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/mocks/mock_scratch_bucket_creator.go
  cli_tools/mocks/mock_storage_client.go
Labels: approved, lgtm, size/L
