Repository GoogleCloudPlatform/compute-image-import, pull requests merged in 2024-03, with the labels that each got.

#141 Add ycohen278 from M2VM as OWNERS_ALIASES.
  OWNERS_ALIASES
Labels: needs-ok-to-test, size/XS, approved, lgtm

#140 Increase disk resize timeout from 5 to 10 minutes.
  daisy_workflows/image_import/import_image.sh
Labels: needs-ok-to-test, size/XS, approved, lgtm

#142 Replace obsolete images.
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
Labels: size/XS, approved, lgtm

#147 update golang.org/x/net, google.golang.org/grpc, golang.org/x/crypto to solve vulnerabilities issues
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools_tests/go.mod
  cli_tools_tests/go.sum
  common/go.mod
  common/go.sum
Labels: approved, lgtm, size/M
